name: CI/CD Workflow

# Trigger workflow on push or pull request to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3   # Check out your code

    # Example: Node.js setup (for frontend React)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run frontend tests
      run: npm test -- --watchAll=false

    # Example: .NET setup (for backend)
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore .NET dependencies
      run: dotnet restore ./backend

    - name: Build .NET project
      run: dotnet build ./backend --configuration Release --no-restore

    - name: Run .NET tests
      run: dotnet test ./backend --no-build --verbosity normal

    # Optional: Deploy step
    # - name: Deploy to GitHub Pages / Azure / Netlify
    #   run: |
    #     echo "Add deployment commands here"
